// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wouguiojiemzcnakueaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvdWd1aW9qaWVtemNuYWt1ZWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MDg0OTQsImV4cCI6MjA1MzA4NDQ5NH0.7Zqw_sYTA2HAgnw_ulPtEUe27Xrixv2MAtVechC8XiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);